services:
    bug.userManager:
        class: BugBundle\Services\UserManager
        arguments: [@service_container]
    bug.trans.helper:
        class: BugBundle\Services\TransHelper
        arguments: [@translator]
    bug.request.decorator:
            class: BugBundle\Services\RequestDecorator

    bug.form.type.user:
        class: BugBundle\Form\Type\UserType
        tags:
            - { name: form.type, alias: bug_user }

    bug.form.type.user.profile:
        class: BugBundle\Form\Type\ProfileType
        tags:
            - { name: form.type, alias: bug_user_profile }

    bug.form.type.role:
        class: BugBundle\Form\Type\RoleType
        tags:
            - { name: form.type, alias: bug_user_role }

    bug.form.type.project:
        class: BugBundle\Form\Type\ProjectType
        tags:
            - { name: form.type, alias: bug_project }

    bug.form.type.issue:
        class: BugBundle\Form\Type\IssueType
        tags:
            - { name: form.type, alias: bug_issue }
        arguments: [@service_container]

