services:
    bug.userManager:
        class: BugBundle\Services\UserManager
        arguments: [@service_container]
    bug.trans.helper:
        class: BugBundle\Services\TransHelper
        arguments: [@translator]
    bug.request.decorator:
            class: BugBundle\Services\RequestDecorator
    bug.activity.manager:
            class: BugBundle\Services\ActivityManager
            arguments:
                - @translator
                - @doctrine
                - @security.token_storage

    bug.form.type.user:
        class: BugBundle\Form\Type\UserType
        tags:
            - { name: form.type, alias: bug_user }

    bug.form.type.user.profile:
        class: BugBundle\Form\Type\ProfileType
        tags:
            - { name: form.type, alias: bug_user_profile }

    bug.form.type.role:
        class: BugBundle\Form\Type\RoleType
        tags:
            - { name: form.type, alias: bug_user_role }

    bug.form.type.project:
        class: BugBundle\Form\Type\ProjectType
        tags:
            - { name: form.type, alias: bug_project }
        arguments: [@service_container]

    bug.form.type.issue:
        class: BugBundle\Form\Type\IssueType
        tags:
            - { name: form.type, alias: bug_issue }
        arguments: [@service_container]

    bug.form.type.issue.comment:
         class: BugBundle\Form\Type\IssueCommentType
         tags:
            - { name: form.type, alias: bug_issue_comment }
         arguments: [@service_container]

    bug.event.listener:
        class: BugBundle\EventListener\EventListener
        tags:
            - {name: doctrine.event_listener, event: postPersist}
            - {name: doctrine.event_listener, event: preUpdate}
            - {name: doctrine.event_listener, event: prePersist}
        arguments: [@event_dispatcher]

    bug.issue.listner:
        class: BugBundle\EventListener\IssueListener
        tags:
            - {name: kernel.event_listener, event: bug.entity.issue.onUpdate, method: onUpdate}
            - {name: kernel.event_listener, event: bug.entity.issue.onPreCreate, method: onPreCreate}
            - {name: kernel.event_listener, event: bug.entity.issue.onAfterCreate, method: onAfterCreate}
        arguments: [@security.token_storage,@bug.activity.manager]

    bug.issue.comment.listner:
        class: BugBundle\EventListener\IssueCommentListener
        tags:
            - {name: kernel.event_listener, event: bug.entity.issuecomment.onUpdate, method: onUpdate}
            - {name: kernel.event_listener, event: bug.entity.issuecomment.onPreCreate, method: onPreCreate}
            - {name: kernel.event_listener, event: bug.entity.issuecomment.onAfterCreate, method: onAfterCreate}
        arguments: [@security.token_storage,@bug.activity.manager]

    security.access.issue_voter:
        class:      BugBundle\Security\IssueVoter
        public:     false
        tags:
            - { name: security.voter }
        arguments: [@doctrine]